name: 'fish-shop/syntax-check'
description: 'A GitHub action for syntax checking fish shell files'
branding:
  icon: 'check'
  color: 'green'
inputs:
  title:
    description: 'Title to display in job summary'
    required: false
    default: 'Syntax check results'
  patterns:
    description: 'File patterns to match against when running syntax checks'
    required: false
    default: '**.fish'
outputs:
  total:
    description: "Total number of files syntax checked"
    value: ${{ steps.syntax-check.outputs.total }}
  passed:
    description: "Number of files passed syntax check"
    value: ${{ steps.syntax-check.outputs.passed }}
  failed:
    description: "Number of files failed syntax check"
    value: ${{ steps.syntax-check.outputs.failed }}
runs:
  using: "composite"
  steps:
    - name: Syntax check fish shell files
      id: syntax-check
      env:
        TITLE: ${{ inputs.title }}
        PATTERNS: ${{ inputs.patterns }}
      run: |
        set -gx TERM xterm-256color

        set -l passed 0
        set -l failed 0

        set title "$TITLE"

        for pattern in (string split --no-empty -- " " $PATTERNS)
            set -l escaped (string escape --style=script --no-quoted -- $pattern)
            set -l escaped (string replace -r -a -- '\\\([?*{}])' '$1' $escaped)

            eval set -l files $escaped

            for file in $files
                echo -n "  "
                set output (fish --no-execute $file 2>&1)
                if test $status -ne 0
                    set_color red; and echo -n "✖"; and set_color normal
                    echo " $file"
                    for line in (string split -- $output)
                        echo "      $line"
                    end
                    set failed (math $failed + 1)
                else
                    set_color green; and echo -n "✔"; and set_color normal
                    echo " $file"
                    set passed (math $passed + 1)
                end
            end
        end

        set -l total (math $passed + $failed)

        echo
        set_color green; and echo -n "passed: $passed"; and set_color normal
        echo -n "  "
        set_color red; and echo -n "failed: $failed"; and set_color normal
        echo "  of $total files"
        echo

        if test $failed -gt 0
            set_color red; and echo "$failed of $total failed."
        else
            set_color green; and echo "All of $total files passed!"
        end

        if test $failed -eq 0
            set result ":white_check_mark: Pass"
        else
            set result ":x: Fail"
        end

        echo "### $title" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "| Result :microscope: | Passed :white_check_mark: | Failed :x: |" >> $GITHUB_STEP_SUMMARY
        echo "|---------------------|---------------------------|------------|" >> $GITHUB_STEP_SUMMARY
        echo "| $result             | $passed                   | $failed    |" >> $GITHUB_STEP_SUMMARY

        echo "total=$total" >> "$GITHUB_OUTPUT"
        echo "passed=$passed" >> "$GITHUB_OUTPUT"
        echo "failed=$failed" >> "$GITHUB_OUTPUT"

        if test $failed -ne 0
            exit 1
        end
      shell: fish {0}
