name: 'fish-shop/syntax-check'
description: 'A GitHub action for syntax checking fish shell files'
branding:
  icon: 'check'
  color: 'green'
inputs:
  pattern:
    description: 'File name pattern'
    required: false
    default: '**.fish'
runs:
  using: "composite"
  steps:
    - run: |
        set failures 0

        for file in ${{ inputs.pattern }}
            set output (fish --no-execute $file 2>&1)
            if test $status -ne 0
                string match --regex --groups-only '^(?<file>.+)\s+\(line\s+(?<line>[0-9]+)\):\s+(?<message>.+)' $output
                set title "Error while reading file $file"
                echo "::error file=$file,line=$line,title=$title::$message"
                set failures (math $failures + 1)
            end
        end

        if test $failures -gt 0
            exit 1
        end
      shell: fish {0}
