name: Dependency Review
on:
  pull_request:
    branches:
      - main

permissions: read-all

jobs:
  dependency-review:
    name: Dependency Review
    permissions:
      pull-requests: write
    uses: fish-shop/workflows/.github/workflows/dependency-review.yml@d7ced0f5d47c0a6a1c55b8b1f3ff9b16b2bcb334 # v1.13.49
