name: Dependency Review
on:
  pull_request:
    branches:
      - main

permissions: read-all

jobs:
  dependency-review:
    name: Dependency Review
    permissions:
      pull-requests: write
    uses: fish-shop/workflows/.github/workflows/dependency-review.yml@3bab619c84f7f115693f78dbe8c7c76f2b7a31fb # v1.14.2
