name: Gitleaks SAST scan
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions: read-all

jobs:
  gitleaks:
    name: Gitleaks SAST scan
    permissions:
      pull-requests: write
    uses: fish-shop/workflows/.github/workflows/gitleaks.yml@28dc0e7b7df42c229e3875504f99f0553fcd1dd1 # v1.14.3
    secrets:
      gitleaks_license: ${secrets.GITLEAKS_LICENSE}
