name: Gitleaks SAST scan
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions: read-all

jobs:
  gitleaks:
    name: Gitleaks SAST scan
    permissions:
      pull-requests: write
    uses: fish-shop/workflows/.github/workflows/gitleaks.yml@4597d09a42cfaa6eaaa0023baf068b958badf522 # v1.13.48
    secrets:
      gitleaks_license: ${secrets.GITLEAKS_LICENSE}
