name: Gitleaks SAST scan
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions: read-all

jobs:
  gitleaks:
    name: Gitleaks SAST scan
    permissions:
      pull-requests: write
    uses: fish-shop/workflows/.github/workflows/gitleaks.yml@06fb481cda13d4b0505d160e025e5eb682771476 # v1.14.4
    secrets:
      gitleaks_license: ${secrets.GITLEAKS_LICENSE}
