name: Markdown Links Check
on:
  pull_request:
    branches:
      - main

permissions: read-all

jobs:
  markdown-links:
    name: Markdown Links Check
    permissions:
      pull-requests: write
    uses: fish-shop/workflows/.github/workflows/markdown-links.yml@f51e302b38504e77ec3d2a6c874a45406bd14aad # v1.14.5
