name: Markdown Links Check
on:
  pull_request:
    branches:
      - main

permissions: read-all

jobs:
  markdown-links:
    name: Markdown Links Check
    permissions:
      pull-requests: write
    uses: fish-shop/workflows/.github/workflows/markdown-links.yml@cc9b0dafea3fc317b270e945841f103f0d3f1048 # v1.14.7
