name: Markdown Links Check
on:
  pull_request:
    branches:
      - main

permissions: read-all

jobs:
  markdown-links:
    name: Markdown Links Check
    permissions:
      pull-requests: write
    uses: fish-shop/workflows/.github/workflows/markdown-links.yml@8ef68690e6bbe9a7aca9a307b2583f07aaa90f59 # v1.14.0
