name: Release Tags
on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+

permissions: read-all

jobs:
  release-tags:
    name: Release Tags
    permissions:
      contents: write
    uses: fish-shop/workflows/.github/workflows/release-tags.yml@d7ced0f5d47c0a6a1c55b8b1f3ff9b16b2bcb334 # v1.13.49
