name: Release Tags
on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+

permissions: read-all

jobs:
  release-tags:
    name: Release Tags
    permissions:
      contents: write
    uses: fish-shop/workflows/.github/workflows/release-tags.yml@8ef68690e6bbe9a7aca9a307b2583f07aaa90f59 # v1.14.0
