name: tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  release:
    types:
      - published
  schedule:
    - cron: '30 19 * * *'
jobs:
  tests:
    strategy:
      matrix:
        os:
          - ubuntu-latest
    runs-on: ${{ matrix.os }}
    steps:
      - run: |
          sudo apt-add-repository --yes ppa:fish-shell/release-3
          sudo apt-get update -qq
          sudo apt-get install --yes fish
